# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more information
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/dbtea

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install libyaml-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            pip install .

      - save_cache:
          paths:
            - ./venv
            - .tox
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - codecov/upload:
          file: coverage.xml
